### PR TITLE
fixed last_first being actually last first for when there're middle names

### PR DESCRIPTION
**Pull request by curlup**
Not sure if it will actually work for all cases where middle name potentially could be written last etc. 
Maybe it would be better to have all possible permutations, but i didnt wanna go implementing before chatting first.

### CODE REVIEW

**Comment by matthewlupo** [comment]
Hey there! Thanks for submitting this pull request. Good catch. As more names are entered with multiple strings, including aka’s in parentheses, it’ll be good to work in use cases for that. I’ll add it to my feature requests to try and catch those 👍 I’ll push this pull request to the live code on the next point release. Probably early tomorrow.

**Comment by curlup** [comment]
Sweet!
BTW is there a roadmap or at least something like a roadmap / backlog maybe?
I wanted to understand what things I might help with or what are the plans to align my proposals with them.

**Review by matthewlupo — APPROVED** [review]
Change approved, adding to `main`

**Comment by matthewlupo** [comment]
Hey there! At this time I don't have a specific roadmap or backlog. Mostly just what Taya requests. I just pushed out a change for an accuracy slider, and the next "features" are changing the color on some labels as well as tooltips.

**Pull request merged**
